version: '3.8'

services:
  matcha-service-front:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    expose:
      - 5000

networks:
  default:
    external:
      name: matcha-network